### ISSUE TITLE
getting error: "No collection param specified on request and no default collection has been set."

### ISSUE THREAD

**Issue by hectoralicea** [Norconex/committer-solr#19]
I'm trying to use a zookeeper Solr Cloud destination for my norconex Committer
```
<solrClientType>CloudSolrClient</solrClientType>
```
and cannot understand how I tell the `com.norconex.committer.solr.SolrCommitter` XML fragment which collection to commit to when the `<solrURL>` that's provided is simply a comma delimited list of hosts with no URL there for no collection name attached to the URL.
```
 *   <dt>CloudSolrClient</dt>
 *     <dd>For use with a SolrCloud cluster. Needs a comma-separated list
 *         of Zookeeper hosts.</dd>
```
as shown here in the comments
https://github.com/Norconex/committer-solr/blob/ac03a9de13fb5ea51104218e28532e430c95dfb8/src/main/java/com/norconex/committer/solr/SolrCommitter.java#L80

The error I'm getting is
```
com.norconex.committer.core.CommitterException: Cannot index document batch to Solr.
	at com.norconex.committer.solr.SolrCommitter.commitBatch(SolrCommitter.java:400)
	at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
	at com.norconex.committer.core.AbstractBatchCommitter.cacheOperationAndCommitIfReady(AbstractBatchCommitter.java:208)
	at com.norconex.committer.core.AbstractBatchCommitter.commitDeletion(AbstractBatchCommitter.java:148)
	at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:225)
	at com.norconex.collector.core.crawler.AbstractCrawler.execute(AbstractCrawler.java:274)
	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:228)
	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:184)
	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:354)
	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:293)
	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:166)
	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:150)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74)
Caused by: org.apache.solr.client.solrj.SolrServerException: No collection param specified on request and no default collection has been set.
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.directUpdate(BaseCloudSolrClient.java:473)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.sendRequest(BaseCloudSolrClient.java:1037)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.requestWithRetryOnStaleState(BaseCloudSolrClient.java:897)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.request(BaseCloudSolrClient.java:829)
	at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1290)
	at com.norconex.committer.solr.SolrCommitter.commitBatch(SolrCommitter.java:394)
	... 14 more
```
my xml fragment for SolrCommitter is
```
      <!-- Decide what to do with your files by specifying a Committer. -->
      <committer class="com.norconex.committer.solr.SolrCommitter">
        <solrClientType>CloudSolrClient</solrClientType>
        <solrURL>172.25.124.190:2181,172.25.124.191:2181,172.25.124.192:2181</solrURL>
        <sourceReferenceField keep="false">document.reference</sourceReferenceField>
        <targetReferenceField>id</targetReferenceField>
        <targetContentField>content</targetContentField>
        <solrUpdateURLParams>
          <param name="fm.ds">927df3075b544785892c6b4c51625714</param>
          <param name="defaultCollection">sample_techproducts_configs</param>
        </solrUpdateURLParams>    
        <commitBatchSize>5</commitBatchSize>
        <queueSize>5</queueSize>
        <maxRetries>2</maxRetries>
        <maxRetryWait>1000</maxRetryWait>
      </committer>
```

**Comment by essiembre** [comment]
Duplicate of https://github.com/Norconex/committer-solr/issues/20
